---
title: "Gyakorlati segédanyag Biostatisztika gyakorlathoz"
author: "Vörös Dániel, Radványi Ádám, Könnyű Balázs"
date: "2020/21/2"
output: 
  bookdown::pdf_book:
    includes:
      in_header: "kell.tex"
      before_body: "titlepage.tex"
always_allow_html: yes
toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache=TRUE)
library(knitr)
library(ggplot2)
library(data.tree)
library(plyr)
library(gridExtra)
#library(DiagrammeR)
library(kableExtra)

hook_output <- knit_hooks$get("output")
knit_hooks$set(output = function(x, options) {
  lines <- options$output.lines
  if (is.null(lines)) {
    return(hook_output(x, options))  # pass to default hook
  }
  x <- unlist(strsplit(x, "\n"))
  more <- "..."
  if (length(lines)==1) {        # first n lines
    if (length(x) > lines) {
      # truncate the output, but add ....
      x <- c(head(x, lines), more)
    }
  } else {
    x <- c(more, x[lines], more)
  }
  # paste these lines together
  x <- paste(c(x, ""), collapse = "\n")
  hook_output(x, options)
})

```

<!-- 1. Bevezetés -->
```{r child="fejezetek/bevezetes.Rmd"}
```

<!-- 1. Ora, matematikai alapok -->
```{r child="fejezetek/matalap.Rmd"}
```

<!-- 1. Ora, R alapok -->
```{r child="fejezetek/ralap.Rmd"}
```

<!-- 2. Ora diszkret eloszlasok -->
```{r child="fejezetek/ora2.Rmd"}
```

<!-- 3. Ora folytonos eloszlasok -->
```{r child="fejezetek/ora3.Rmd"}
```

<!-- 3. Ora Adatok -->
```{r child="fejezetek/adat.Rmd"}
```

```{r child="fejezetek/abrazolas.Rmd"}
```




<!-- 5. Ora meroszamok -->
```{r child="fejezetek/meroszamok.Rmd"}
```

<!-- 6. Ora konfidencia intervallumok -->
```{r child="fejezetek/konfint.Rmd"}
```


<!-- 7. Ora hipotezis vizsgalotak -->
```{r child="fejezetek/hipotvizsg.Rmd"}
```


<!-- Fuggelek -->
```{r child="fejezetek/fuggelek.Rmd"}
```
