
# Matematikai alapok (1. óra)

A tárgy előfeltétele a *Matematika GY* tárgy, mely megad sok olyan matematikai alapkészséget, melyekre a hallgatóknak szükségük van. Vannak azonban a tárgynak nagy hiányosságai is. Sok ilyen hiányossággal nem tudnak a *Biostatisztika* tárgy oktatói foglalkozni, mivel nem áll rendelkezésükre megfelelő mennyiségű idő. Ezek közé tartozik a **deriválás** és **integrálás** is. Ezért csak kérhetem a motiváltabb hallgatókat, hogy nézzenek utána ezen fogalmak lényegének.  
Amivel foglalkozni tudunk, az két, az előadáson és gyakorlat során is gyakran használt operátor: a *szumma* és a *produktum*.

## A *szumma* operátor

Ha egy hosszabb számsorozat (pl. egy vektor) tagjainak az összegét akarjuk kiszámolni, felírhatjuk a megfelelő egyenletet a számsorozat tagjainak felsorolásával is, mint:
$$ x_1 + x_2 + x_3 + ... +x_n, $$
ahol egy sorozat tagjait összeadjuk az első tagtól az *n*-edikig. A alsó indexbe tett számok a számsorozat tagjait jelölik (*index*). A *szumma* ($\sum$) operátor azonban, erre egy sokkal egyszerűbb és kényelmesebb megoldást nyújt. A *szumma* operátor után következő kifejezés megadja az összeadandó produktum tagjait, míg az operátor alatt és felett sorra megadhatjuk egy új (az *index*) változó segítségével, hogy a számsorozat mely tagjait kívánjuk összeadni. Például az előző kifejezés a *szumma* operátor segítségével leírva így nézne ki:
$$ \sum_{i=1}^{n}{x_i} = x_1 + x_2 + x_3 + \dots +x_n  $$
Itt az $x_i$ jelöli a számsorozat tagjait, az $i$ pedig az *index* változó, amit a *szumma* jel alatt és felett definiáltunk. A *szumma* jel alatt szoktuk definiálni az új változó kezdeti értékét, felette pedig az utolsó értékét. Itt például az $i$ 1-től $n$-ig fut: 1, 2, 3, ..., $n$. Tegyük fel, hogy $x$ egy vektor:

\begin{equation}
x =
\begin{pmatrix} 
10 \\ 
20 \\
30 \\
\vdots \\
90
\end{pmatrix}
\end{equation}

Ekkor az egyenletünket így számolhatjuk ki ($x$ első tagja 10, a második 20, és így tovább):

$$ \sum_{i=1}^{n}{x_i} = x_1 + x_2 + x_3 + ... +x_n = 10+20+30+\dots + 90 = 450 $$

Ha nincs semmi a *szumma* operátor alá és fölé írva, akkor az összes tagot összeadjuk. Ebben az esetben

$$ \sum{x_i} = \sum_{i=1}^{n}{x_i} $$

Ha csak a második és a harmadik tag összegét akarjuk kiszámolni, azt így tehetjük meg:

$$ \sum_{i=2}^{3}{x_i} = x_2 + x_3 = 20+30 = 50 $$

Tehetünk bonyolultabb tagokat is a *szumma* jel után. Például az előző vektor elemeinek négyzetösszege (az elemeit négyzetükre emeljük és ennek összegét vesszük):

$$ \sum_{i=1}^{n}{x_i^2} = x_1^2 + x_2^2 + x_3^2 + ... +x_n^2 = 10^2+20^2+30^2+\dots + 90^2 = 28500 $$

Nem csak előre megadott sorozatokra lehet alkalmazni a *szumma* operátort:

$$ \sum_{i=1}^{5}{i} = 1 +2 +3+4+5=15$$
Itt az $i$ index értékei voltak az összeadandó tagok, amit az operátoron belül definiáltuk.
Egy bonyolultabb példa: 

$$ \sum_{j=1}^{3}{(10^i+1)} = (10^1+1)+(10^2+1)+(10^3+1)=11+101+1001= 1113$$
Ha az $i$ index helyébe először behelyettesítünk 1-et, akkor $10^1+1$-et kapunk, ha 2-őt, akkor $10^2+1$-et, stb. és aztán ezeket mind összeadjuk.
Az előbbi egyenletet át is alakíthatjuk:

$$ \sum_{j=1}^{3}{(10^i+1)} = \sum_{j=1}^{3}{10^i} + \sum_{j=1}^{3}{1}=\sum_{j=1}^{3}{10^i} + 3 = \\ = 10+100+1000+3=1113 $$
Az összegből először kiemeljük az $i$-t tartalmazó tagokat, így kapjuk a két *szummás* tagot, melyből a második egy konstans szám (1) háromszori összeadása következik (amit elég könnyen kiszámíthatunk). Ennél az egyenletnél ez ugyan felesleges rendezgetésnek tűnhet, de később még hasznos lesz a gyakorlat során.  
Egy másik példa az átrendezésre:

$$\sum_{i=2}^{4}{i/3} = 2/3+3/3+4/3= 0.667 + 1.000 + 1.333 = 3$$
A gyakorlottabbak a bonyolult tizedes törtekkel való dolgozás helyett így is megoldhatják:

$$\sum_{i=2}^{4}{i/3} = 2/3+3/3+4/3 = \frac{1}{3}(2+3+4)= {2+3+4 \over 3} = {9 \over 3} =3 $$

Egy számítógép azonban  nem fog nekiállni átrendezni az egyenleteinket, hanem egyesével kiszámolja a tagokat és összeadja, így kettővel több osztási műveletet végezne el, mint ami feltétlenül szükséges. Így érdemes formailag is átrendezni az egyenletet:

$$\sum_{i=2}^{4}{i/3} = \sum_{i=2}^{4}{1 \over 3}{i} ={1 \over 3} \sum_{i=2}^{4}{i}  ={\sum_{i=2}^{4}{i} \over 3} = {2+3+4 \over 3} =3 $$

A *szumma* műveleteket egymásba is ágyazhatjuk, tehát a külső operátort egy belső operátorra alkalmazzuk:

$$\sum_{a=0}^{2}{ \sum_{b=10}^{12}{b^a} } = \sum_{a=0}^{2}{ (10^a + 11^a +12^a) } = $$
$$ = (10^0 + 11^0 +12^0) + (10^1 + 11^1 +12^1) + (10^2 + 11^2 +12^2)= $$ 
$$ = 1+1+1+10+11+12+100+121+144 = 401$$
Ilyen esetekben először vesszük a külső *szumma* első értékét (ami itt $a=0$), majd elvégezzük a belső *szumma* operátor alapján az összeadást, amit a $b=0$ értékkel kezdünk (azaz $10^0 + 11^0 +12^0$). Majd vesszük $a=1$ értéket, és elvégezzük vele a belső operátor alapján az összeadást újra (eredmény: $10^1 + 11^1 +12^1$), és ezt az összeget hozzáadjuk az előző eredményekhez (eddig: $10^0 + 11^0 +12^0 + 10^1 + 11^1 +12^1$). Ezt folytatjuk mindaddig, amíg tart a külső operátor számlálója, vagyis $a = 2$-ig.

## A *produktum* operátor

A *produktum* operátor ($\prod{}$) hasonlít a *szumma* operátorhoz azzal a kivétellel, hogy a tagokat nem összeadni kell, hanem összeszorozni. Így:

$$ \prod_{i=1}^{10}{i} = 1 \cdot 2 \cdot 3 \cdot ... \cdot 10= 3628800$$

Eggyel bonyolultabb művelet:

$$ \prod_{i=-1}^{2}{2^i}=(2^{-1}) \cdot (2^0) \cdot (2^1) \cdot (2^2)=0.5 \cdot 1 \cdot 2 \cdot 4=4$$

 
